#!/bin/bash
# ======================================================================
# Verify the mobile-core C ABI has not drifted from its frozen shape.
#
# Source: Verification Scripts §5; Team Prompt 5 §3.3 ("generated by
# cbindgen from Rust").
#
# mobile-core's C header (crates/mobile-core/mobile-core.h) is the actual
# contract between the Rust core and the Swift/Kotlin FFI callers built
# on top of it. cbindgen regenerates it from src/ on every build, so a
# signature change is silent at the Rust layer -- it compiles, tests
# pass, mobile-core.h is happily rewritten -- while iOS/Android code that
# still calls the old shape (wrong argument count, a pointer where a
# value now is, a renamed function) fails only at link time or, worse,
# at runtime with a stack smash, on a platform this repo cannot build or
# test on directly (see network-blocks-google-endpoints.md /
# desktop-shell-is-standalone.md: mobile targets only build on CI). A
# check that catches the drift here, before it ever reaches a mobile
# build, is the only place this class of bug is affordable to catch.
#
# Method: regenerate the header with the same cbindgen settings
# build.rs uses (crates/mobile-core/build.rs), and diff it against the
# frozen baseline at crates/mobile-core/expected_ffi.h. Any difference
# -- added, removed, renamed, or reordered/retyped declarations -- is a
# drift and fails the check. Updating the baseline is a deliberate,
# reviewed act: `cp crates/mobile-core/mobile-core.h
# crates/mobile-core/expected_ffi.h` after confirming the ABI change is
# intended.
#
# If cbindgen is not installed, the check FAILS with an install
# instruction. It deliberately does not skip or pass: a gate that
# passes when its own tool is missing is worse than no gate, because it
# looks green while checking nothing.
# ======================================================================

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

FAILED=0
CRATE_DIR="crates/mobile-core"
EXPECTED="$CRATE_DIR/expected_ffi.h"

echo "Verifying mobile-core FFI (C ABI) has not drifted..."
echo ""

# ----------------------------------------------------------------------
# 1. cbindgen must be installed. A missing tool must fail loud, not pass
#    silently -- see header comment.
# ----------------------------------------------------------------------
echo "  [1/3] cbindgen is installed"
if ! command -v cbindgen >/dev/null 2>&1; then
    echo "    [FAIL] cbindgen not found on PATH."
    echo ""
    echo "    Install it with:"
    echo "      cargo install cbindgen --version 0.27.0 --locked"
    echo ""
    echo "    (0.27 matches the [build-dependencies] pin in"
    echo "    $CRATE_DIR/Cargo.toml.)"
    echo ""
    echo "[FAIL] Cannot verify the FFI ABI without cbindgen."
    exit 1
fi
CBINDGEN_VERSION="$(cbindgen --version 2>&1 || true)"
echo "    ok ($CBINDGEN_VERSION)"

# ----------------------------------------------------------------------
# 2. The frozen baseline must exist. Without it there is nothing to diff
#    against, and the check cannot pass vacuously.
# ----------------------------------------------------------------------
echo "  [2/3] frozen baseline exists: $EXPECTED"
if [ ! -f "$EXPECTED" ]; then
    echo "    [FAIL] $EXPECTED not found."
    echo "    Establish it deliberately with:"
    echo "      cp $CRATE_DIR/mobile-core.h $EXPECTED"
    FAILED=1
else
    echo "    ok"
fi

# ----------------------------------------------------------------------
# 3. Regenerate the header with build.rs's own cbindgen settings and
#    diff it against the frozen baseline.
#
# build.rs configures the Builder with Language::C and a fixed header
# comment via `.with_header(...)`. The cbindgen CLI has NO equivalent
# flag (confirmed against `cbindgen --help`: no --with-header option; a
# custom header is only settable via the Rust Builder API or a
# `header = "..."` key in a cbindgen.toml, and this crate has neither).
# So a plain `cbindgen --lang c` run from the crate dir does NOT
# reproduce build.rs's output byte-for-byte: build.rs's header
# insertion also leaves a blank line between the banner and the first
# `#include`, which the bare CLI run never produces (having no banner
# to begin with). Stripping only the banner line and leaving that
# stray blank line in the baseline's normalized output fails the diff
# on every run -- including immediately after (re-)establishing the
# baseline from current, unchanged code (verified: this was caught
# empirically as a live false positive during review). Both the banner
# line and any leading blank line(s) it left behind are normalized out
# of both sides before the diff, so the comparison is over ABI content
# only.
# ----------------------------------------------------------------------
echo "  [3/3] generated header matches frozen baseline"
if [ $FAILED -eq 0 ]; then
    TMP_HEADER="$(mktemp)"
    trap 'rm -f "$TMP_HEADER"' EXIT

    # TMP_HEADER is already absolute (from mktemp), so it must NOT be
    # prefixed with the crate dir we cd into below -- doing so would
    # silently write to the wrong path and make the later diff compare
    # a stale/empty file, passing when the ABI actually drifted.
    if ! (cd "$CRATE_DIR" && cbindgen --lang c --quiet -o "$TMP_HEADER" .) 2>"$TMP_HEADER.err"; then
        echo "    [FAIL] cbindgen failed to generate the header:"
        sed 's/^/      /' "$TMP_HEADER.err"
        rm -f "$TMP_HEADER.err"
        FAILED=1
    else
        rm -f "$TMP_HEADER.err"
        # Drop the leading "Generated by cbindgen..." banner line (or
        # any comment line) from both sides before comparing -- it is
        # not part of the ABI, and its exact wording is a build.rs
        # implementation detail this check has no stake in. Also strip
        # any leading blank line(s) left behind: build.rs's header
        # insertion leaves one after the banner, but the bare CLI
        # invocation (no banner at all) never has one -- without this,
        # that formatting difference alone fails the diff even when the
        # ABI is byte-for-byte identical (see comment above).
        NORM_EXPECTED="$(mktemp)"
        NORM_GENERATED="$(mktemp)"
        DIFF_OUT="$(mktemp)"
        trap 'rm -f "$TMP_HEADER" "$NORM_EXPECTED" "$NORM_GENERATED" "$DIFF_OUT"' EXIT
        grep -v '^// Generated by cbindgen' "$EXPECTED" | sed '/./,$!d' > "$NORM_EXPECTED"
        grep -v '^// Generated by cbindgen' "$TMP_HEADER" | sed '/./,$!d' > "$NORM_GENERATED"

        if diff -u "$NORM_EXPECTED" "$NORM_GENERATED" >"$DIFF_OUT" 2>&1; then
            echo "    ok"
        else
            echo "    [FAIL] mobile-core's C ABI has drifted from the frozen baseline:"
            echo ""
            sed 's/^/      /' "$DIFF_OUT"
            echo ""
            echo "    If this drift is intentional, update the baseline after review:"
            echo "      cp $CRATE_DIR/mobile-core.h $EXPECTED"
            FAILED=1
        fi
    fi
else
    echo "    skipped (no baseline to diff against)"
fi

echo ""
if [ $FAILED -eq 0 ]; then
    echo "[PASS] mobile-core FFI ABI matches the frozen baseline"
    exit 0
else
    echo "[FAIL] mobile-core FFI ABI check failed"
    exit 1
fi
