apiVersion: v1
kind: Service
metadata:
  name: {{ include "onyx-api.fullname" . }}-stable
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "onyx-api.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "onyx-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: {{ .Values.service.httpPort }}, targetPort: http}
    - {name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onyx-api.fullname" . }}-canary
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "onyx-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: {{ .Values.service.httpPort }}, targetPort: http}
