[package]
name = "local-blob-storage"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
query-application.workspace = true
async-trait.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
