#!/usr/bin/env node
/**
 * Syncs shared/i18n/{en,fa}.json (+ React runtime) into every web frontend:
 *   web-ui, mobile-pwa, desktop-shell/ui, admin-shell/ui
 *
 * Generates src/i18n/dictionaries.generated.ts from JSON so no tsconfig
 * change (resolveJsonModule) is needed anywhere.
 *
 * Usage: node scripts/sync-i18n.mjs [--check]
 */
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const auditArg = process.argv.find((arg) => arg.startsWith("--audit-scope="));
const auditScope = auditArg ? auditArg.slice("--audit-scope=".length) : null;

const en = JSON.parse(readFileSync(join(root, "shared/i18n/en.json"), "utf8"));
const fa = JSON.parse(readFileSync(join(root, "shared/i18n/fa.json"), "utf8"));

const enKeys = Object.keys(en).sort();
const faKeys = Object.keys(fa).sort();
const missingInFa = enKeys.filter((k) => !(k in fa));
const missingInEn = faKeys.filter((k) => !(k in en));
if (missingInFa.length > 0 || missingInEn.length > 0) {
  console.error("i18n key mismatch:");
  if (missingInFa.length > 0) console.error("  missing in fa.json:", missingInFa.join(", "));
  if (missingInEn.length > 0) console.error("  missing in en.json:", missingInEn.join(", "));
  process.exit(1);
}

const generated = `// AUTO-GENERATED by scripts/sync-i18n.mjs — do not edit by hand.
// Source: shared/i18n/{en,fa}.json
export const en: Record<string, string> = ${JSON.stringify(en, null, 2)} as Record<string, string>;
export const fa: Record<string, string> = ${JSON.stringify(fa, null, 2)} as Record<string, string>;
export const dictionaries = { en, fa } as const;
export type Locale = "en" | "fa";
`;

function auditUserFacingLiterals(scope) {
  const extensions = new Set([".ts", ".tsx"]);
  const ignored = new Set(["node_modules", "dist", "build", ".git"]);
  const violations = [];

  function walk(dir) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (ignored.has(entry.name)) continue;
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (extensions.has(entry.name.slice(entry.name.lastIndexOf(".")))) {
        const source = readFileSync(full, "utf8");
        const jsxText = />\s*([A-Za-z][^<>{}\n]{2,})\s*</g;
        for (const match of source.matchAll(jsxText)) {
          const value = match[1].trim();
          if (!value || value.startsWith("//")) continue;
          violations.push(`${full}: ${value}`);
        }
      }
    }
  }

  walk(join(root, scope));
  if (violations.length) {
    console.error("i18n literal audit failed. User-facing JSX text must use t(...) keys:");
    for (const violation of violations) console.error(`  ${violation}`);
    process.exit(1);
  }
  console.log(`i18n literal audit passed: ${scope}`);
}

if (auditScope) auditUserFacingLiterals(auditScope);

const targets = [
  "web-ui/src/i18n",
  "mobile-pwa/src/i18n",
  "crates/bins/desktop-shell/ui/src/i18n",
  "crates/bins/admin-shell/ui/src/i18n",
];

const staticFiles = ["I18nContext.tsx", "LanguageSwitcher.tsx", "rtl.css"];

let changed = 0;
for (const rel of targets) {
  const dir = join(root, rel);
  mkdirSync(dir, { recursive: true });
  const genPath = join(dir, "dictionaries.generated.ts");
  const prev = existsSync(genPath) ? readFileSync(genPath, "utf8") : null;
  if (prev !== generated) {
    if (check) {
      console.error(`OUT OF SYNC: ${rel}/dictionaries.generated.ts (run: node scripts/sync-i18n.mjs)`);
      changed++;
    } else {
      writeFileSync(genPath, generated);
      console.log(`wrote ${rel}/dictionaries.generated.ts (${enKeys.length} keys)`);
    }
  }
  for (const f of staticFiles) {
    const src = join(root, "shared/i18n/react", f);
    const dst = join(dir, f === "rtl.css" ? "rtl.css" : f);
    const srcText = readFileSync(src, "utf8");
    const prevText = existsSync(dst) ? readFileSync(dst, "utf8") : null;
    if (prevText !== srcText) {
      if (check) {
        console.error(`OUT OF SYNC: ${rel}/${f}`);
        changed++;
      } else {
        copyFileSync(src, dst);
        console.log(`copied ${rel}/${f}`);
      }
    }
  }
}

if (check && changed > 0) process.exit(1);
console.log(check ? "i18n in sync." : "i18n sync complete.");
