apiVersion: v1
kind: Service
metadata:
  name: {{ include "onyx-api-relay.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "onyx-api-relay.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "onyx-api-relay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - {name: http, port: {{ .Values.service.httpPort }}, targetPort: http}
    - {name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics}
