//! Generates `mobile-core.h` from the FFI-exported items in `src/lib.rs`,
//! per Team Prompt 5 §3.3 ("generated by cbindgen from Rust"). Real,
//! current `cbindgen` (0.27) API — verified against its own docs before
//! writing this.

fn main() {
    println!("cargo:rerun-if-changed=src");
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header(
            "// Generated by cbindgen from the mobile-core Rust crate. Do not edit by hand.",
        )
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file("mobile-core.h");
        }
        Err(e) => {
            // A header-generation failure shouldn't silently fail the
            // whole build (mobile targets aren't buildable in every
            // environment — e.g. this sandbox has no Xcode/Android NDK,
            // per Team 4's established precedent), but it also shouldn't
            // be swallowed entirely.
            println!("cargo:warning=cbindgen header generation failed: {e}");
        }
    }
}
