// Generated by cbindgen from the mobile-core Rust crate. Do not edit by hand.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for an active event subscription, matching the header's
 * `typedef struct EventSubscription EventSubscription;`. Holds the
 * `JoinHandle` for the forwarding task so `mobile_core_unsubscribe` can
 * abort it — `client-composition`'s `Subscription` itself has no
 * `unsubscribe()` (it simply stops being polled when dropped), so the
 * task doing the polling is what needs to be told to stop.
 */
typedef struct EventSubscription EventSubscription;

/**
 * Opaque handle returned to the caller, matching the C header's
 * `typedef struct MobileApp MobileApp;` (Team Prompt 5 §3.3). Holds its
 * own dedicated tokio runtime (mobile apps have no ambient async
 * runtime the way a `#[tokio::main]` binary does) plus the same
 * `AppState` `desktop-shell` builds.
 */
typedef struct MobileApp MobileApp;

/**
 * Initializes the mobile core. Returns a handle, or null on failure
 * (invalid arguments, or the async setup work — opening the SQLite pool,
 * applying migrations — failing). Team Prompt 5 §3.3.
 *
 * # Safety
 * `db_path` and `config_json` must each be a valid, NUL-terminated C
 * string pointer.
 */
struct MobileApp *mobile_core_new(const char *db_path, const char *config_json);

/**
 * Populates (or replaces) the local Task/Mission approval-authority
 * cache from `hierarchy_json` — the same `[{id, parent_user_id,
 * is_admin}, ...]` shape `GET /api/users/hierarchy` returns.
 *
 * # Why this is a separate call, not part of `mobile_core_new`'s config
 * A real design decision, not an assumption: `mobile_core_new` must
 * succeed (opening the local SQLite pool, applying migrations) before
 * any network call could possibly happen, and mobile has no login/auth
 * concept of its own at the FFI layer (see `client_composition::
 * hierarchy_cache`'s module doc — the org's reporting-line directory
 * is fetched from Dart's already-authenticated `OnyxHttpApi`, not
 * re-fetched independently here). Baking hierarchy data into
 * `mobile_core_new`'s `config_json` would force login+fetch to
 * complete before local-database bootstrap could even start, coupling
 * two things that don't need to be coupled and that happen at
 * genuinely different times (`mobile_core_new` once per process;
 * login/hierarchy-fetch whenever the person actually signs in, which
 * may be well after the app — and its offline local data — is already
 * usable). A separate call the Dart side invokes right after both
 * `mobile_core_new` and its own HTTP fetch succeed keeps those two
 * timelines independent.
 *
 * Returns `0` on success, `-1` on invalid arguments (null pointer,
 * non-UTF8 string) or if `hierarchy_json` fails to parse as the
 * expected shape (see `HierarchyCache::load_from_json`'s own error
 * cases — an id that isn't a valid UUID, malformed JSON).
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`.
 * `hierarchy_json` must be a valid, NUL-terminated C string pointer.
 */
int32_t mobile_core_set_hierarchy(struct MobileApp *handle, const char *hierarchy_json);

/**
 * Runs one background synchronization cycle against the registered mobile
 * core instance. Intended for iOS `BGAppRefreshTask` and Android WorkManager.
 */
int32_t mobile_core_background_sync_registered(uint64_t task_id);

/**
 * Frees the mobile core handle. Team Prompt 5 §3.3.
 *
 * # Safety
 * `handle` must be a pointer previously returned by `mobile_core_new`,
 * not yet freed, and not used again after this call.
 */
void mobile_core_free(struct MobileApp *handle);

/**
 * Frees a string returned by the mobile core. Team Prompt 5 §3.3.
 *
 * # Safety
 * `str` must be a pointer previously returned by one of this crate's
 * functions (`mobile_core_execute_command`/`_execute_query`), not yet
 * freed, and not used again after this call.
 */
void mobile_core_free_string(char *str);

/**
 * Background sync entry point (Android). Called from `WorkManager`.
 * Returns 1 if work was done, 0 if idle. Team Prompt 5 §3.3/§4.3.
 *
 * # Safety
 * Same handle-parameter deviation as `mobile_core_ios_background_sync`
 * (`ios_background.rs`) — the frozen contract's literal signature
 * (`mobile_core_android_do_work(void* env, void* thiz)`, JNI
 * convention) also has no way to reach a specific `MobileApp` instance.
 * `env`/`thiz` are accepted and ignored (real JNI plumbing — resolving
 * `thiz` to a stored native handle field — is Android-toolchain-specific
 * code this sandbox cannot build or verify, per the same "no NDK"
 * constraint as the rest of this crate's mobile-specific pieces).
 */
int mobile_core_android_do_work(struct MobileApp *handle, void *_env, void *_thiz);

/**
 * Executes a command. Returns a JSON string with the result (the caller
 * must free it via `mobile_core_free_string`), or null on failure
 * (invalid arguments, or a dispatch error — the error itself is not
 * currently surfaced to the caller as anything richer than "null";
 * flagged, not silently treated as complete, since Team Prompt 5 §3.3
 * doesn't specify an error-reporting mechanism for this function beyond
 * "returns JSON string with the result"). Team Prompt 5 §3.3.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`. `command_json`
 * must be a valid, NUL-terminated C string pointer.
 */
char *mobile_core_execute_command(struct MobileApp *handle, const char *command_json);

/**
 * Triggers a sync session manually. Returns 0 on success, -1 on error.
 * Team Prompt 5 §3.3. Uses `SyncAgent::trigger_sync_now` — added to
 * `client-composition` specifically because this FFI function needed it
 * and no prior increment/ruling had defined a manual-trigger entry
 * point (`SyncAgent`'s only previous entry point was its own internal
 * periodic loop).
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`.
 */
int mobile_core_trigger_sync(struct MobileApp *handle);

/**
 * Subscribes to events. Returns a subscription handle; the callback is
 * invoked for each matching event (JSON string). Team Prompt 5 §3.3.
 *
 * # Safety
 * `handle` must be valid. `filter_json` must be a valid NUL-terminated
 * C string. `callback` must be a valid function pointer that remains
 * valid for as long as the returned subscription is alive (i.e. until
 * `mobile_core_unsubscribe` is called) — this is inherently unsafe
 * FFI-callback lifetime management the C/Swift/Kotlin caller is
 * responsible for upholding; Rust cannot enforce it.
 */
struct EventSubscription *mobile_core_subscribe_events(struct MobileApp *handle,
                                                       const char *filter_json,
                                                       void (*callback)(const char*));

/**
 * Unsubscribes and frees the subscription. Team Prompt 5 §3.3.
 *
 * # Safety
 * `sub` must be a pointer previously returned by
 * `mobile_core_subscribe_events`, not yet freed.
 */
void mobile_core_unsubscribe(struct EventSubscription *sub);

/**
 * Uploads the file at `path` from the local filesystem, returning a
 * JSON string (caller must free via `mobile_core_free_string`) with the
 * same shape as `client_composition::file_upload::UploadOutcome`
 * (`file_asset_id`, `upload_session_id`, `content_hash`, `size_bytes`).
 * Returns null on any failure — invalid arguments, an unreadable file,
 * or a coordinator error.
 *
 * MIME type is hardcoded to `"application/octet-stream"`, matching
 * `desktop-shell::upload_file`'s own documented choice: no MIME-sniffing
 * library is a workspace dependency, and guessing from the file
 * extension alone would be a half-measure that silently mislabels
 * files. A real content-type detector is a follow-up for both clients,
 * not something to invent differently here.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`. `path`,
 * `organization_id`, `user_id`, and `device_id` must each be valid,
 * NUL-terminated C string pointers.
 */
char *mobile_core_upload_file(struct MobileApp *handle,
                              const char *path,
                              const char *organization_id,
                              const char *user_id,
                              const char *device_id);

/**
 * Downloads the file content stored under `content_hash`, writing it to
 * `destination_path` on the local filesystem. Returns the number of
 * bytes written, or `-1` on any failure (invalid arguments, no stored
 * content for that hash, or a write error) -- mirrors
 * `desktop-shell::download_file`'s `u64`-bytes-written /
 * `InvalidArgument` contract, adapted to a C-ABI-friendly `i64` sentinel
 * since FFI has no `Result` to return through.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`.
 * `content_hash` and `destination_path` must each be valid,
 * NUL-terminated C string pointers.
 */
int64_t mobile_core_download_file(struct MobileApp *handle,
                                  const char *content_hash,
                                  const char *destination_path);

/**
 * Lists locally stored aggregate projections for one aggregate type.
 * Returns a JSON array ordered by most recently updated first.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`. `aggregate_type`
 * must be a valid, NUL-terminated C string pointer.
 */
char *mobile_core_list_aggregates(struct MobileApp *handle, const char *aggregate_type);

/**
 * Returns the current local-first synchronization state as JSON.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`.
 */
char *mobile_core_get_sync_status(struct MobileApp *handle);

/**
 * Returns all currently open synchronization conflicts as JSON.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`.
 */
char *mobile_core_list_conflicts(struct MobileApp *handle);

/**
 * Resolves an open conflict using `local`, `remote`, or `escalate`.
 * `conflict_json` must contain the serialized `conflict_id` field returned
 * by `mobile_core_list_conflicts`.
 *
 * # Safety
 * `handle` must be a valid pointer from `mobile_core_new`. `conflict_json`
 * and `resolution` must each be a valid, NUL-terminated C string pointer.
 */
int mobile_core_resolve_conflict(struct MobileApp *handle,
                                 const char *conflict_json,
                                 const char *resolution);

/**
 * Executes a query. Returns a JSON string with the result. Team Prompt
 * 5 §3.3.
 *
 * # Safety
 * Same contract as `mobile_core_execute_command`.
 */
char *mobile_core_execute_query(struct MobileApp *handle, const char *query_json);

/**
 * Background sync entry point (iOS). Called from `BGAppRefreshTask`.
 * Returns 1 if work was done, 0 if idle. Team Prompt 5 §3.3/§4.3.
 *
 * # Session resumption (flagged, not silently assumed complete)
 * Team Prompt 5 §4.3 requires persisting `SyncCursor` across app
 * suspension and resuming a *new* `SynchronizationSession` from it on
 * the next background run. `SynchronizationSession` has no
 * cursor-argument constructor or `resume(cursor)` — `pause()`/`resume()`
 * operate on the same session instance's internal state (see R2/W1,
 * `DECISIONS.md`), which cannot survive process death. This function
 * therefore runs a fresh, full sync cycle (`trigger_sync_now`) rather
 * than genuine cursor-based resumption — real §4.3 compliance is
 * blocked on `SynchronizationSession` gaining a real resumption API, a
 * change to Increment 3's delivered type this crate has no mandate to
 * make unilaterally.
 *
 * # Safety
 * `handle`, not `task_id`, is the actual pointer parameter here — Team
 * Prompt 5 §3.3's C signature is `mobile_core_ios_background_sync(uint64_t
 * task_id)` with **no handle parameter at all**, which cannot work: the
 * function has no way to reach a `MobileApp` instance without one. This
 * is a genuine gap in the frozen contract's own C header, not a
 * transcription error — flagged rather than silently worked around by
 * inventing global mutable state (a `static` handle) to paper over it,
 * since that would itself be a significant, silent architectural choice
 * (global state, single-instance assumption) the frozen contract never
 * asked for either. Implemented here taking an explicit handle,
 * deviating from the literal C signature; the real Swift caller
 * (`BackgroundService.swift` in Team Prompt 5 §3.5) would need to be
 * updated to pass one.
 */
int mobile_core_ios_background_sync(struct MobileApp *handle, uint64_t _task_id);
